-- 1

select * from sol_6_1;
SELECT DISTINCT
    ASIGNATURA
FROM 
    IMPARTIR 
WHERE 
    PROFESOR = (SELECT ID FROM PROFESORES WHERE UPPER (NOMBRE || ' ' || APELLIDO1) = 'MANUEL ENCISO');

    
-- 2

select * from docencia.sol_6_2;
SELECT 
    ALUMNO 
FROM 
    MATRICULAR 
WHERE 
   (GRUPO, CURSO, ASIGNATURA) IN 
    (SELECT GRUPO, CURSO, ASIGNATURA
    FROM IMPARTIR
    WHERE PROFESOR = 'C-34-TU-00');
-- 3

 
select * from sol_3_2;

SELECT 
    D.NOMBRE, SUM(A.CREDITOS)
FROM ASIGNATURAS A JOIN DEPARTAMENTOS D ON (A.DEPARTAMENTO = D.CODIGO)
GROUP BY A.DEPARTAMENTO, D.NOMBRE           --El A.DEPARTAMENTO NO ES NECESARIO
ORDER BY 2 DESC;

-- 4

select * from sol_3_4;

SELECT 
    P.DESPACHO, SUM(I.CARGA_CREDITOS) TOTAL_CREDITOS
FROM 
    ASIGNATURAS A 
    JOIN IMPARTIR I ON (I.ASIGNATURA = A.CODIGO)
    JOIN PROFESORES P ON (I.PROFESOR = P.ID)
WHERE 
    P.DESPACHO IS NOT NUll  
GROUP BY P.DESPACHO;


-- 5

select * from sol_3_8;

SELECT DISTINCT
    M.ALUMNO, M.ASIGNATURA CODIGO, ASI.NOMBRE
FROM
    MATRICULAR M 
    JOIN ASIGNATURAS ASI ON M.ASIGNATURA = ASI.CODIGO
WHERE   
    (M.ALUMNO, ASI.CREDITOS) 
IN 
    (SELECT M2.ALUMNO, MAX(A.CREDITOS)
     FROM ASIGNATURAS A JOIN MATRICULAR M2 ON A.CODIGO = M2.ASIGNATURA
     GROUP BY M2.ALUMNO)
ORDER BY 1,2,3;   


-- 6

select * from sol_3_10;
SELECT 
    D.NOMBRE DEPARTAMENTO, A.NOMBRE ASIGNATURA
FROM 
    DEPARTAMENTOS D 
    JOIN ASIGNATURAS A ON D.CODIGO = A.DEPARTAMENTO
WHERE     
    (D.CODIGO,A.CREDITOS) IN
    (SELECT DEPARTAMENTO, MIN(CREDITOS)
    FROM ASIGNATURAS 
    GROUP BY DEPARTAMENTO);
-- 7

select * from sol_3_13;

SELECT 
    D.NOMBRE DEPARTAMENTO
FROM 
    DEPARTAMENTOS D
    JOIN ASIGNATURAS A ON A.DEPARTAMENTO = D.CODIGO
GROUP BY 
    D.NOMBRE
HAVING 
    COUNT(A.NOMBRE) = 
        (SELECT MAX(COUNT(A2.NOMBRE))
        FROM  DEPARTAMENTOS D2 JOIN ASIGNATURAS A2 ON A2.DEPARTAMENTO = D2.CODIGO
        GROUP BY D2.NOMBRE);

-- 8

select * from sol_3_15;
SELECT 
    P.NOMBRE, P.APELLIDO1, NVL(P.APELLIDO2, ' ' ) APELLIDO2
FROM 
    PROFESORES P
WHERE (P.ID) IN 
    (
        SELECT PROFESOR 
        FROM IMPARTIR 
        GROUP BY 
            PROFESOR 
        HAVING 
            SUM(CARGA_CREDITOS) > (SELECT AVG(SUM(CARGA_CREDITOS)) FROM IMPARTIR GROUP BY PROFESOR)
    );
-- 9

select * from sol_3_18; 
SELECT DISTINCT
    NOMBRE 
FROM    
    DEPARTAMENTOS 
WHERE 
    CODIGO NOT IN (SELECT DEPARTAMENTO FROM ASIGNATURAS WHERE CREDITOS > 6);   
-- 10

select * from sol_3_20;
SELECT 
    P1.NOMBRE || ' ' || P1.APELLIDO1 || ' ' || P1.APELLIDO2 PROFESOR1,
    P2.NOMBRE || ' ' || P2.APELLIDO1 || ' ' || P2.APELLIDO2 PROFESOR2
FROM 
    PROFESORES P1, PROFESORES P2

WHERE 
    P1.ID < P2.ID 
AND    
    (P1.ID,P2.ID) 
NOT IN
    (SELECT 
        I1.PROFESOR, I2.PROFESOR
     FROM 
        IMPARTIR I1 NATURAL JOIN MATRICULAR M1,
        IMPARTIR I2 NATURAL JOIN MATRICULAR M2
     WHERE 
        M1.ALUMNO = M2.ALUMNO);
