-- 1
select * from sol_2_5;

SELECT 
    P.ID, P.NOMBRE, P.APELLIDO1, P.APELLIDO2, ASI.CODIGO, ASI.NOMBRE ASIGNATURA

FROM
    PROFESORES P
    JOIN IMPARTIR I ON I.PROFESOR = P.ID
    JOIN  ASIGNATURAS ASI ON ASI.CODIGO = I.ASIGNATURA;
-- 2

select * from sol_5_2;

SELECT 
    P1.NOMBRE, P1.APELLIDO1, P1.APELLIDO2, NVL(P2.ID,'No tiene') DIRECTOR_TESIS
FROM 
    PROFESORES P1 LEFT JOIN PROFESORES P2 ON (P1.DIRECTOR_TESIS = P2.ID);
-- 3

select * from sol_2_8;

SELECT 
    P1.NOMBRE nombrep1, P1.APELLIDO1 apellido1p1, P1.APELLIDO2 apellido2p1, TRUNC(MONTHS_BETWEEN(SYSDATE,P1.ANTIGUEDAD)/12) Antiguedad1,
    P2.NOMBRE nombrep2, P2.APELLIDO1 apellido1p2, P2.APELLIDO2 apellido2p2, TRUNC(MONTHS_BETWEEN(SYSDATE,P2.ANTIGUEDAD)/12) Antiguedad2
FROM 
    PROFESORES P1, PROFESORES P2
WHERE 
    P1.ID < P2.ID
AND    
    ABS((MONTHS_BETWEEN(SYSDATE,P1.ANTIGUEDAD)/12) - (MONTHS_BETWEEN(SYSDATE,P2.ANTIGUEDAD)/12)) < 2
AND
    P1.DEPARTAMENTO = P2.DEPARTAMENTO;
    

-- 4

select * from sol_2_10;

SELECT 
    A1.NOMBRE AS "Asignatura 1", A2.NOMBRE  AS "Asignatura 2", A3.NOMBRE AS "Asignatura 3", A1.COD_MATERIA AS Materia
FROM 
    ASIGNATURAS A1, ASIGNATURAS A2, ASIGNATURAS A3
WHERE 
    A1.CODIGO < A2.CODIGO
AND 
    A2.CODIGO < A3.CODIGO
AND 
    A1.COD_MATERIA = A2.COD_MATERIA
AND
    A2.COD_MATERIA= A3.COD_MATERIA;

-- 5

select * from sol_2_12;

SELECT 
    A.NOMBRE, A.APELLIDO1, A.APELLIDO2
FROM
    ALUMNOS A
    JOIN MATRICULAR M ON A.DNI = M.ALUMNO
    JOIN ASIGNATURAS ASI ON ASI.CODIGO = M.ASIGNATURA
    JOIN IMPARTIR I ON I.ASIGNATURA = ASI.CODIGO
    JOIN PROFESORES P ON P.ID = I.PROFESOR
WHERE 
    I.ASIGNATURA = M.ASIGNATURA
AND
    I.GRUPO = M.GRUPO
AND 
    I.CURSO = M.CURSO
AND 
    UPPER(P.NOMBRE) = 'ENRIQUE'
AND 
    UPPER(P.APELLIDO1) ='SOLER'
ORDER BY 2,3,1;
    
    
-- 6

select * from sol_2_14;

 
SELECT
    A.NOMBRE Asignatura, M.NOMBRE Materia, P.NOMBRE || ' ' || P.APELLIDO1 || ' ' || P.APELLIDO2 AS Profesor, I.CARGA_CREDITOS
FROM
    ASIGNATURAS A 
    JOIN MATERIAS M ON M.CODIGO = A.COD_MATERIA
    JOIN IMPARTIR I ON I.ASIGNATURA = A.CODIGO
    JOIN PROFESORES P ON P.ID = I.PROFESOR
WHERE 
    CARGA_CREDITOS IS NOT NULL
ORDER BY
    M.CODIGO, 
    A.NOMBRE DESC;

    
-- 7

select * from sol_2_15;
SELECT
    A.NOMBRE Asignatura, D.NOMBRE Departamento, A.CREDITOS, ROUND((A.PRACTICOS/A.CREDITOS)*100,2) AS "%Prácticos"
FROM 
    ASIGNATURAS A
    JOIN DEPARTAMENTOS D ON A.DEPARTAMENTO = D.CODIGO
WHERE 
    A.CREDITOS IS NOT NULL
AND
    A.PRACTICOS IS NOT NULL
AND 
    A.TEORICOS IS NOT NULL
ORDER BY 4 DESC;
    

-- 8

select * from sol_2_19;

    SELECT APELLIDO1 AS Apellidos
    FROM ALUMNOS
    WHERE UPPER (APELLIDO1) LIKE '%LL%'
UNION 
    SELECT APELLIDO2 AS Apellidos
    FROM ALUMNOS
    WHERE UPPER (APELLIDO2) LIKE '%LL%'
UNION    
    SELECT APELLIDO1 AS Apellidos
    FROM PROFESORES
    WHERE UPPER (APELLIDO1) LIKE '%LL%'
UNION 
    SELECT APELLIDO2 AS Apellidos
    FROM PROFESORES
    WHERE UPPER (APELLIDO2) LIKE '%LL%';   
    
-- 9

select * from sol_2_23;

SELECT 
    'El director de ' || P1.NOMBRE || ' ' || P1.APELLIDO1 || ' es ' || P2.NOMBRE || ' ' ||  P2.APELLIDO1 || ' ' || P2.APELLIDO2 AS TESIS,
    NVL(I.TRAMOS,0) TRAMOS
FROM
    PROFESORES P1 
    JOIN PROFESORES P2 ON P1.DIRECTOR_TESIS = P2.ID
    LEFT JOIN INVESTIGADORES I ON P2.ID = I.ID_PROFESOR;

-- 10

select * from sol_2_24;

SELECT 
    A1.NOMBRE AS ALUMNO_1_NOMBRE, 
    A1.APELLIDO1 AS ALUMNO_1_APELLIDO1, 
    A1.APELLIDO2 AS ALUMNO_1_APELLIDO2, 
    A2.NOMBRE AS ALUMNO_2_NOMBRE, 
    A2.APELLIDO1 AS ALUMNO_2_APELLIDO1, 
    A2.APELLIDO2 AS ALUMNO_2_APELLIDO2
FROM
    ALUMNOS A1 
    LEFT JOIN ALUMNOS A2
        ON
            A1.FECHA_PRIM_MATRICULA = A2.FECHA_PRIM_MATRICULA
            AND A1.DNI < A2.DNI 
ORDER BY 2,3,1;